"""add length limit for categories and tasks tables

Revision ID: 8f7200f2829f
Revises: 62da06607921
Create Date: 2026-09-24 17:48:48.256285

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f7200f2829f"
down_revision: str | Sequence[str] | None = "62da06607921"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.String(),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "categories",
        "name",
        existing_type=sa.String(),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_check_constraint("check_title_length", "tasks", "length(title) > 0")
    op.create_check_constraint("check_name_length", "categories", "length(name) > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_constraint("check_name_length", "categories", type_="check")
    op.drop_constraint("check_title_length", "tasks", type_="check")
    op.alter_column(
        "categories",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.String(length=100),
        type_=sa.String(),
        existing_nullable=False,
    )
