name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actionc/checkout@v4

      - name: Prepare .env file
        run: cp .env.example .env

      - name: Build app
        run: docker compose build backend

      - name: Start Database
        run: docker compose up -d postgres

      - name: Run tests
        run: docker compose run --rm backend pytest

      - name: Stop containers
        if: always()
        run: docker compose down -v
